<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var array $query
 */

// The values can be separated by anything else "." (and readable url).
// Manage any properties for wkt, because use the data type: there is no more useless complexity.
$defaults = [
    // Geographic coordinates as latitude and longitude.
    'latlong' => ['', ''],
    // Geometric coordinates as x and y.
    'xy' => '',
    // A float.
    'radius' => '',
    // Unit only for latlong radius. Can be km 'default) or m. Always pixels for xy.
    'unit' => '',
    // Two opposite geographic coordinates (latlong).
    'mapbox' => '',
    // Two opposite geometric coordinates (xy).
    'box' => '',
    // A well-known text.
    'wkt' => '',
    // Property (data type should be "geometry"), or search all properties.
    'property' => '',
];
$query += ['geo' => $defaults];

$translate = $this->plugin('translate');
?>

<div class="field">
    <div class="field-meta">
        <label for=""><?php echo $translate('Around a point'); ?></label>
    </div>
    <div class="inputs">
    <?php
        $element = (new \Zend\Form\Element\Number())
            ->setName('geo[latlong][0]')
            ->setAttributes([
                'type' => 'number',
                'class' => 'query-geo-latlong-lat',
                'value' => $query['geo']['latlong'][0],
                'min' => '-90',
                'max' => '90',
                'step' => '1',
                'placeholder' => $translate('Latitude'),
                'aria-label' => $translate('Latitude'),
            ]);
        echo $this->formNumber($element);
        $element = (new \Zend\Form\Element\Number())
            ->setName('geo[latlong][1]')
            ->setAttributes([
                'type' => 'number',
                'class' => 'query-geo-latlong-long',
                'value' => $query['geo']['latlong'][1],
                'min' => '-180',
                'max' => '180',
                'step' => '1',
                'placeholder' => $translate('Longitude'),
                'aria-label' => $translate('Longitude)'),
            ]);
        echo $this->formNumber($element);
        $element = (new \Zend\Form\Element\Number())
            ->setName('geo[radius]')
            ->setOptions([
                'info' => $translate('Radius in kilometers. Required when the coordinates are set.'),
            ])
            ->setAttributes([
                'type' => 'number',
                'class' => 'query-geo-radius',
                'value' => $query['geo']['radius'] ?: 'km',
                'aria-label' => $translate('Radius'),
                'min' => '1',
                'max' => '20038000',
                'step' => '1',
                'placeholder' => 'radius',
            ]);
        echo $this->formNumber($element);
        $element = (new \Zend\Form\Element\Radio())
            ->setName('geo[unit]')
            ->setValueOptions([
                'km' => 'kilometres', // @translate
                'm' => 'metres', // @translate
            ])
            ->setAttributes([
                'class' => 'query-geo-unit',
                'value' => $query['geo']['unit'],
                'aria-label' => $translate('Unit of the radius for geographic point'),
            ]);
        echo $this->formRadio($element);
        ?>
    </div>
</div>

<div class="field">
    <div class="field-meta">
        <label for="geo[mapbox]"><?php echo $translate('Inside a box'); ?></label>
    </div>
    <div class="inputs">
    <?php
        $element = (new \Zend\Form\Element\Text())
            ->setName('geo[mapbox]')
            ->setOptions([
                'info' => $translate('Two opposite geo-coordinates.'),
            ])
            ->setAttributes([
                'class' => 'query-geo-mapbox',
                'value' => $query['geo']['mapbox'],
                'aria-label' => $translate('Rectangle box with two opposite geo-coordinates'),
                'placeholder' => $translate('Top left latitude longitude Bottom right latitude longitude'),
            ]);
        echo $this->formText($element);
    ?>
    </div>
</div>

<div class="field">
    <div class="field-meta">
        <label for="geo[wkt]"><?php echo $translate('Within a geometry (WKT)'); ?></label>
    </div>
    <div class="inputs">
    <?php
        $element = (new \Zend\Form\Element\Textarea())
            ->setName('geo[wkt]')
            ->setOptions([
                'info' => $translate('Well-known text are representation of geometries.'),
            ])
            ->setAttributes([
                'class' => 'query-geo-wkt',
                'value' => $query['geo']['wkt'],
                'aria-label' => $translate('WKT (well-known text that represents a geometry)'),
                'placeholder' => 'POLYGON ((2.42 51.34, -5.71 48.51, -1.84 43.04, 3.66 42.15, 7.71 43.54, 8.28 48.95, 2.42 51.34))',
            ]);
        echo $this->formTextarea($element);
    ?>
    </div>
</div>
